# Generated by Django 4.2 on 2024-03-08 13:22

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitalservice',
            name='name',
        ),
        migrations.RemoveField(
            model_name='hospitalservice',
            name='price',
        ),
        migrations.RemoveField(
            model_name='location',
            name='name',
        ),
        migrations.AlterField(
            model_name='hospitalprofile',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospital', to='profiles.location', verbose_name='Location of the hospital'),
        ),
        migrations.AlterField(
            model_name='hospitalprofile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='KE'),
        ),
        migrations.AlterField(
            model_name='hospitalservice',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='profiles.location', verbose_name='Location of the patient'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='KE'),
        ),
    ]
