# Generated by Django 4.2 on 2024-03-08 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('medical_records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.hospitalprofile'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='Medical Record Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='profiles.patientprofile'),
        ),
    ]
