# Generated by Django 4.2 on 2024-03-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0002_medicalrecord_hospital_medicalrecord_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='diagnosis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='prescribed_medications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='symptoms',
            field=models.TextField(blank=True, null=True),
        ),
    ]
